# Eksplorasi Raisin Dataset

Notebook ini digunakan untuk memahami struktur Raisin Dataset sebelum dilakukan eksperimen Machine Learning.

Tujuan:
- Memuat dataset.
- Melihat ukuran dan struktur data.
- Mengidentifikasi fitur dan label.
- Memisahkan fitur (`X`) dan label (`y`).
- Memeriksa distribusi kelas.
- Memeriksa missing value.

In [5]:
import pandas as pd

## 1. Memuat Dataset

Raisin Dataset berisi karakteristik geometris kismis yang digunakan untuk membedakan dua kelas, yaitu Kecimen dan Besni.

Dataset dimuat menggunakan Pandas agar dapat dianalisis dalam bentuk tabel.

In [6]:
df = pd.read_excel(
    "../../data/raisin/Raisin_Dataset.xlsx"
)

In [7]:
df.head()

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter,Class
0,87524,442.246011,253.291155,0.819738,90546,0.758651,1184.040,Kecimen
1,75166,406.690687,243.032436,0.801805,78789,0.684130,1121.786,Kecimen
2,90856,442.267048,266.328318,0.798354,93717,0.637613,1208.575,Kecimen
3,45928,286.540559,208.760042,0.684989,47336,0.699599,844.162,Kecimen
4,79408,352.190770,290.827533,0.564011,81463,0.792772,1073.251,Kecimen

## 2. Ukuran Dataset

Ukuran dataset diperiksa untuk mengetahui jumlah sampel dan jumlah kolom yang tersedia.

In [8]:
df.shape

(900, 8)

In [9]:
df.columns

Index(['Area', 'MajorAxisLength', 'MinorAxisLength', 'Eccentricity',
       'ConvexArea', 'Extent', 'Perimeter', 'Class'],
      dtype='str')

## 3. Memisahkan Fitur dan Label

Kolom `Class` merupakan label yang ingin diprediksi.

Tujuh kolom lainnya merupakan fitur yang digunakan model untuk mempelajari karakteristik masing-masing jenis kismis.

In [10]:
X = df.drop("Class", axis=1)
y = df["Class"]

In [11]:
X.head()

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter
0,87524,442.246011,253.291155,0.819738,90546,0.758651,1184.040
1,75166,406.690687,243.032436,0.801805,78789,0.684130,1121.786
2,90856,442.267048,266.328318,0.798354,93717,0.637613,1208.575
3,45928,286.540559,208.760042,0.684989,47336,0.699599,844.162
4,79408,352.190770,290.827533,0.564011,81463,0.792772,1073.251

In [12]:
y.head()

0    Kecimen
1    Kecimen
2    Kecimen
3    Kecimen
4    Kecimen
Name: Class, dtype: str

## 4. Distribusi Kelas

Distribusi kelas diperiksa untuk mengetahui jumlah sampel dari masing-masing jenis kismis.

In [13]:
y.value_counts()

Class
Kecimen    450
Besni      450
Name: count, dtype: int64

## 5. Pemeriksaan Missing Value

Missing value diperiksa untuk memastikan tidak terdapat data kosong yang dapat mengganggu proses training dan evaluasi model.

In [14]:
df.isnull().sum().sum()

np.int64(0)

## 6. Tipe Data

Tipe data setiap kolom diperiksa untuk memastikan seluruh fitur dapat digunakan dalam proses Machine Learning.

In [15]:
df.dtypes

Area                 int64
MajorAxisLength    float64
MinorAxisLength    float64
Eccentricity       float64
ConvexArea           int64
Extent             float64
Perimeter          float64
Class                  str
dtype: object

## Kesimpulan Eksplorasi Awal

Raisin Dataset terdiri dari sekitar 900 sampel dengan 7 fitur numerik dan 1 label kelas.

Dataset memiliki dua kelas, yaitu Kecimen dan Besni, dengan distribusi kelas yang seimbang.

Dataset selanjutnya akan digunakan untuk menguji Decision Tree, KNN, dan Random Forest menggunakan 30 variasi random seed pada pembagian data training dan testing.